##
## see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - echo "==> install"
      - make -C apps/authorize deps
      - make -C apps/token deps
      - make -C apps/client deps
      - npm --prefix cloud install
      - npm --prefix js/signin install

  pre_build:
    commands:
      - echo "==> pre build"
  build:
    commands:
      - echo "==> build"
      - make -C apps/authorize
      - make -C apps/authorize dist
      - make -C apps/token
      - make -C apps/token dist
      - make -C apps/client
      - make -C apps/client dist
      - make -C js/signin VSN=${BUILD_RELEASE}

  post_build:
    commands:
      - echo "==> post build"
      - (cd cloud && cdk deploy oauth2-api-${BUILD_RELEASE} -c vsn=${BUILD_RELEASE})
      - make -C js/signin dist-up VSN=${BUILD_RELEASE}
