##
## see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - |-
        echo "==> install"
      - (cd cloud; npm install)

  pre_build:
    commands:
      - |-
        echo "==> pre build"
  build:
    commands:
      - |-
        echo "==> build"
      # - npm run build

  post_build:
    commands:
      - |-
        echo "==> post build"
      - |-
          case $BUILD in
            CleanUp)
              #(cd cloud; VSN=${BUILD_RELEASE} cdk destroy -f)
              ;;
            *)
              #(cd cloud; VSN=${BUILD_RELEASE} cdk deploy)
              ;;
          esac