##
## see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - echo "==> install"
      - make deps

  pre_build:
    commands:
      - echo "==> testing"
      - make test

  build:
    commands:
      - echo "==> build"
      - make dist

  post_build:
    commands:
      - echo "==> post build"
      - (cd cloud && cdk deploy oauth2-api-${BUILD_RELEASE} -c vsn=${BUILD_RELEASE} -c domain=${CONFIG_DOMAIN} -c email=${CONFIG_EMAIL} -c cert=${CONFIG_TLS_CERT})
      - make -C js/signin dist-up VSN=${BUILD_RELEASE}
      - make -C js/account dist-up VSN=${BUILD_RELEASE}
