##
## This Docker Compose file may be modified and distributed under the terms
## of the MIT license.  See the LICENSE file for details.
## https://github.com/fogfish/makefile
##
## @doc
##   An example docker compose file to spawn Erlang releases  
##
## @version 1.0.0
version: '3'
services:

  ##
  aws-ddb:
    build: ./test/mock/ddb
    ports:
      - "8000:8000"

  ##
  oauth2:
    build:
      context: .
      dockerfile: _build/spawner

    ports:
      - "8080:8080"

    environment:
      ## required to reduce Erlang VM memory footprint 
      - "CODE_LOADING_MODE=interactive"

      ## fake keys to use mock deployment of ddb
      - "AWS_ACCESS_KEY_ID=access"
      - "AWS_SECRET_ACCESS_KEY=secret"

      ## OAuth2 appliance config 
      - "OAUTH2_STORAGE=ddb+http://aws-ddb:8000/oauth2pubkey?hashkey=access"
      - "OAUTH2_PUBLIC=openssl+public:///tmp"
      - "OAUTH2_SECRET=openssl+secret:///tmp"

