##
## @doc
##   OAuth2 service
version: '2'
services:
  
  ##
  oauth2:
    image: fogfish/oauth2
    mem_limit: 128m
    ports:
      - "8443:8443"

    ## configure logging 
    logging:
      driver: awslogs
      options:
        awslogs-group: my-cluster
        awslogs-region: eu-west-1
        awslogs-stream-prefix: oauth2

    environment:
      ## required to reduce Erlang VM memory footprint 
      - "CODE_LOADING_MODE=interactive"

      ## service discovery feature
      - "SERVICE_FQDN=auth.example.com"

      ## Enable DynamoDB as storage back-end 
      ## You might need to configure AWS Region only
      - "OAUTH2_STORAGE=ddb+https://dynamodb.eu-west-1.amazonaws.com:443/live-oauth2-pubkey?hashkey=access"

      ## Server port and protocol, see Enable Secure Transport Layer if you need https
      - "OAUTH2_PORT=http://*:8443"
      - "OAUTH2_TLS_CERTIFICATE=none"
      - "OAUTH2_TLS_PRIVATE_KEY=none"

      ## define claim issuer
      ## RFC 7519   
      ##    4.1.1.  "iss" (Issuer) Claim
      - "OAUTH2_ISSUER=http://auth.example.com:8443"

      ## define claim audience
      ## RFC 7519
      ##   4.1.3.  "aud" (Audience) Claim
      - "OAUTH2_AUDIENCE=any"

      ## comma separated list of default claim scopes
      - "OAUTH2_CLAIMS=uid=true"

      ##
      ## configure token(s) time-to-live in seconds
      - "OAUTH2_TTL_ACCESS_TOKEN=3600"
      - "OAUTH2_TTL_REFRESH_TOKEN=86400"
      - "OAUTH2_TTL_EXCHANGE_CODE=60"



