##
## @doc
##   OAuth2 service
version: '2'
services:
  
  ##
  oauth2:
    image: fogfish/oauth2
    mem_limit: 32m
    ports:
      - "8081:8080"

    environment:
      ## required to reduce Erlang VM memory footprint 
      - "CODE_LOADING_MODE=interactive"

      ## service discovery feature
      - "SERVICE_FQDN=auth.example.com"

      ## oAuth2 appliance config 
      - "OAUTH2_STORAGE=ddb+https://dynamodb.eu-west-1.amazonaws.com:443/live-oauth2pubkey?hashkey=access"
      - "OAUTH2_PUBLIC=openssl+public:///usr/local/oauth2/releases"
      - "OAUTH2_SECRET=openssl+secret:///usr/local/oauth2/releases"
