##
## @doc
##   backing services required by oauth2
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Spawn AWS resource for OAuth2 service.
Parameters:

  Env:
    Type: String
    Default: dev
    Description: |
      service environment 

##
##
Resources:

  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Env}-oauth2-pubkey

      AttributeDefinitions:
        -
          AttributeName: access
          AttributeType: S
        -
          AttributeName: master
          AttributeType: S

      KeySchema:
        -
          AttributeName: access
          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

      GlobalSecondaryIndexes:
        -
          IndexName: master
          KeySchema:
            -
              AttributeName: master
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - access
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  OAuth2IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${Env}-oauth2-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"

      Policies:
        - PolicyName: !Sub ${Env}-oauth2-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:

              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Sub arn:aws:dynamodb:*:*:table/${Env}-oauth2-pubkey
