##
##
version: '2'
services:
  
  ##
  aws-ddb:
    build: ./ddb/
    ports:
      - "8000:8000"

  ##
  oauth2:
    image: fogfish/oauth2
    ports:
      - "8080:8080"

    environment:
      - "AWS_ACCESS_KEY_ID=access"
      - "AWS_SECRET_ACCESS_KEY=secret"
      - "OAUTH2_STORAGE=ddb+http://aws-ddb:8000/oauth2pubkey?hashkey=access"
